/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.RegexRenamer;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author doogi
 */
public class RegexRenamerUI extends javax.swing.JFrame {

    /**
     * Creates new form RegexRenamerUI
     */
    
    private String[] extensions_list;
    
    private boolean rename_folders = true;   
    private boolean enter_folders = true;
    
            
    public RegexRenamerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        renameFolderToggleButton1 = new javax.swing.JToggleButton();
        enterFolderToggleButton2 = new javax.swing.JToggleButton();
        extensionsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exIgnoreRadioButton1 = new javax.swing.JRadioButton();
        exRenameRadioButton2 = new javax.swing.JRadioButton();
        submitButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        regexTextField1 = new javax.swing.JTextField();
        replaceTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        renameFolderToggleButton1.setText("Rename Folders");
        renameFolderToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameFolderToggleButton1ActionPerformed(evt);
            }
        });

        enterFolderToggleButton2.setText("Enter Folders");
        enterFolderToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterFolderToggleButton2ActionPerformed(evt);
            }
        });

        extensionsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extensionsTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Comma separated file extension");

        buttonGroup2.add(exIgnoreRadioButton1);
        exIgnoreRadioButton1.setText("Ignore");
        exIgnoreRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exIgnoreRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(exRenameRadioButton2);
        exRenameRadioButton2.setText("Only rename");
        exRenameRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exRenameRadioButton2ActionPerformed(evt);
            }
        });

        submitButton1.setText("Submit");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Regex Commands");

        jLabel3.setText("Regex");

        regexTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexTextField1ActionPerformed(evt);
            }
        });

        replaceTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Replace Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton1)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extensionsTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exIgnoreRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exRenameRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(regexTextField1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterFolderToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(renameFolderToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regexTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(renameFolderToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enterFolderToggleButton2)
                        .addComponent(exRenameRadioButton2))
                    .addComponent(exIgnoreRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extensionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extensionsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extensionsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extensionsTextFieldActionPerformed

    private void exIgnoreRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exIgnoreRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exIgnoreRadioButton1ActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        // TODO add your handling code here:
        // When submit button is pressed, do renaming actions
        System.out.printf("Rename Folders: [%s]%n", rename_folders);
        System.out.printf("Enter Folders: [%s]%n", enter_folders);
    }//GEN-LAST:event_submitButton1ActionPerformed

    private void replaceTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceTextField1ActionPerformed

    private void regexTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regexTextField1ActionPerformed

    private void renameFolderToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameFolderToggleButton1ActionPerformed
        // If button is pressed, change boolean to ignore renaming folders, and
        // change Text of button to reflect change
        this.rename_folders = !this.rename_folders;
        
        if(this.rename_folders)
            renameFolderToggleButton1.setText("Rename Folders");
        else
            renameFolderToggleButton1.setText("Ignore Renaming Folders");
    }//GEN-LAST:event_renameFolderToggleButton1ActionPerformed

    private void enterFolderToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterFolderToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.enter_folders = !this.enter_folders;
        if(this.enter_folders)
            enterFolderToggleButton2.setText("Enter Folders");
        else
            enterFolderToggleButton2.setText("Do Not Enter Folders");
    }//GEN-LAST:event_enterFolderToggleButton2ActionPerformed

    private void exRenameRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exRenameRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exRenameRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegexRenamerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegexRenamerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegexRenamerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegexRenamerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegexRenamerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JToggleButton enterFolderToggleButton2;
    private javax.swing.JRadioButton exIgnoreRadioButton1;
    private javax.swing.JRadioButton exRenameRadioButton2;
    private javax.swing.JTextField extensionsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField regexTextField1;
    private javax.swing.JToggleButton renameFolderToggleButton1;
    private javax.swing.JTextField replaceTextField1;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
